# Generated by Django 4.0.4 on 2022-04-17 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, help_text='Código UUID  único não sequencial', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='Ativo')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Data da criação do registro', verbose_name='Data da criação')),
                ('created_time', models.TimeField(auto_now_add=True, help_text='Hora da criação do registro', verbose_name='Hora da criação')),
                ('time', models.TimeField(help_text='Hora marcada pelo usuário para o serviço', verbose_name='Horário')),
                ('date', models.DateField(help_text='Data marcada pelo usuário para o serviço', verbose_name='Data')),
                ('service', models.CharField(choices=[('1', 'Serviço 1'), ('2', 'Serviço 2'), ('3', 'Serviço 3'), ('4', 'Serviço 4'), ('5', 'Serviço 5')], help_text='O serviço que será oferecido ao usuário', max_length=5, verbose_name='Tipo do serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
