# Generated by Django 4.0.3 on 2022-04-03 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID Código único não sequencial', unique=True, verbose_name='UUID')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Data da criação do registro', verbose_name='Data de criação')),
                ('created_time', models.TimeField(auto_now_add=True, help_text='Hora da criação do registro', verbose_name='Hora de criação')),
                ('active', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='Ativo')),
                ('avaliable_plataforms', models.CharField(choices=[('W', 'Web'), ('M', 'Mobile'), ('D', 'Desktop'), ('WM', 'Web e Mobile'), ('WD', 'Web e Desktop'), ('MD', 'Mobile e Desktop'), ('MWD', 'Web e Mobile e Desktop')], default='W', max_length=3)),
            ],
            options={
                'db_table': 'System',
            },
        ),
    ]
